# Generated by Django 6.0.3 on 2026-03-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bmi',
            new_name='blood_sugar',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='glucose',
            new_name='height',
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='drug',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='physical_activity',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
