# Generated by Django 6.0.3 on 2026-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_bmi_patient_blood_sugar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='disease',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='drug',
            new_name='drug_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='blood_sugar',
            new_name='exercise_hours_per_week',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='alcohol',
            new_name='medication_use',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='physical_activity',
            new_name='obesity',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol_consumption',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='diet',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='income',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='physical_activity_days_per_week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_heart_problems',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sedentary_hours_per_day',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sleep_hours_per_day',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='stress_level',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='triglycerides',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(max_length=10),
        ),
    ]
